import styles from '../styles/Home.module.css'
import { useMantineTheme, Text} from "@mantine/core"

export default function Home() {
  const theme = useMantineTheme()
  return (
    <>
      <Text>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Iaculis eu non diam phasellus vestibulum lorem sed risus. Ultrices dui sapien eget mi proin sed. Massa tincidunt dui ut ornare lectus sit. Vestibulum sed arcu non odio euismod. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Accumsan tortor posuere ac ut. Blandit cursus risus at ultrices mi tempus imperdiet. Scelerisque felis imperdiet proin fermentum. Id faucibus nisl tincidunt eget. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Turpis egestas maecenas pharetra convallis posuere morbi leo. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Lorem ipsum dolor sit amet. Duis ultricies lacus sed turpis tincidunt id.

Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Nulla facilisi cras fermentum odio eu feugiat pretium. Sodales ut etiam sit amet nisl purus in mollis nunc. Est lorem ipsum dolor sit amet. At tellus at urna condimentum mattis pellentesque id nibh. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Egestas fringilla phasellus faucibus scelerisque. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Viverra tellus in hac habitasse platea. Ultrices in iaculis nunc sed augue lacus. Consequat nisl vel pretium lectus.

At in tellus integer feugiat scelerisque. Pellentesque nec nam aliquam sem et tortor. Tempor orci eu lobortis elementum nibh. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Vitae tortor condimentum lacinia quis vel eros donec ac. Et tortor consequat id porta nibh venenatis. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Lacus sed viverra tellus in hac. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst quisque. Tempus egestas sed sed risus. Egestas erat imperdiet sed euismod nisi porta lorem. Eget arcu dictum varius duis at consectetur lorem donec massa. Et netus et malesuada fames ac turpis egestas integer. Aliquet nibh praesent tristique magna sit amet purus gravida quis.

Vitae elementum curabitur vitae nunc sed velit dignissim. Faucibus a pellentesque sit amet porttitor eget. Neque laoreet suspendisse interdum consectetur libero id. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet sit amet. Mauris augue neque gravida in fermentum et. Id interdum velit laoreet id donec ultrices. Eu sem integer vitae justo eget magna fermentum. Eu sem integer vitae justo eget. Porttitor eget dolor morbi non. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Vel facilisis volutpat est velit egestas. Bibendum ut tristique et egestas quis. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Nulla facilisi nullam vehicula ipsum a. Pharetra massa massa ultricies mi. Aliquam sem fringilla ut morbi tincidunt augue interdum velit.

Mattis rhoncus urna neque viverra justo nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Suspendisse in est ante in nibh mauris. Eu consequat ac felis donec et odio. Ultrices tincidunt arcu non sodales neque sodales. Tempor id eu nisl nunc mi ipsum. Adipiscing commodo elit at imperdiet dui accumsan. Congue nisi vitae suscipit tellus. Morbi tristique senectus et netus et malesuada fames. Euismod quis viverra nibh cras pulvinar mattis. Sit amet facilisis magna etiam tempor orci. Nec sagittis aliquam malesuada bibendum. A scelerisque purus semper eget. Gravida cum sociis natoque penatibus et magnis dis.

Suspendisse ultrices gravida dictum fusce ut placerat orci. Volutpat diam ut venenatis tellus in metus vulputate eu. Justo nec ultrices dui sapien eget. Vestibulum lorem sed risus ultricies. Ut etiam sit amet nisl purus. Feugiat in fermentum posuere urna. Vitae congue mauris rhoncus aenean vel. Pharetra diam sit amet nisl. Id aliquet lectus proin nibh nisl condimentum id venenatis. Tincidunt dui ut ornare lectus sit amet est placerat. Suspendisse potenti nullam ac tortor vitae. Faucibus a pellentesque sit amet porttitor eget dolor. Nunc vel risus commodo viverra. In mollis nunc sed id semper risus in hendrerit gravida. Nunc congue nisi vitae suscipit tellus mauris a diam. Sit amet mattis vulputate enim nulla. Varius vel pharetra vel turpis nunc eget lorem. Amet est placerat in egestas erat. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. A iaculis at erat pellentesque.

Cum sociis natoque penatibus et. Pellentesque nec nam aliquam sem et tortor consequat id porta. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Velit aliquet sagittis id consectetur purus ut faucibus. Eleifend mi in nulla posuere sollicitudin aliquam ultrices. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Non diam phasellus vestibulum lorem sed. Ac auctor augue mauris augue neque. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Nec ultrices dui sapien eget mi proin sed libero enim. Orci eu lobortis elementum nibh tellus molestie. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Nulla facilisi nullam vehicula ipsum a. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mattis enim ut tellus elementum sagittis. Tempor orci eu lobortis elementum nibh tellus. Pulvinar elementum integer enim neque volutpat ac. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus.

Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Cum sociis natoque penatibus et magnis dis. Et ligula ullamcorper malesuada proin libero nunc. Consectetur lorem donec massa sapien faucibus et molestie. Pharetra et ultrices neque ornare aenean euismod. Quisque id diam vel quam elementum pulvinar etiam non. Et tortor at risus viverra adipiscing at in. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Volutpat sed cras ornare arcu dui vivamus.
      </Text>
    </>
  )
}
